name = "SMGStats"
uuid = "69244843-d0fa-4a00-9bc2-bde15b166b8b"
authors = ["Nick Owens <owensnick@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
OnlineStats = "a15396b6-48d5-5d58-9928-6d29437db91e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SMGReader = "1fcad8e2-2524-48d4-84b4-e3c1a79e288e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
